name: GH App- Run Semgrep Scan on Dispatch

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [zcs-event]

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APP_CLONE_REPO_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_CLONE_REPO_PRIVATE_KEY }}      
      
      - name: Checkout different repository
        uses: actions/checkout@v2
        with:
          repository: Nitin-Personal/javaspringvulny
          # repository:  ${{ github.event.client_payload.repository_full_name }}   # <username>/<repository-name>
          # ref: 'master' # ${{ github.event.client_payload.commit }} # <branch, tag, or commit>
          token: ${{ steps.get_workflow_token.outputs.token }}
          
      - name: Clone External Repository
        run: |
          # # Replace 'https://' with 'https://{PAT}@' in the GIT_URL
          # modified_url=$(echo "${GIT_URL}" | sed "s|https://|https://${PAT_READ_ONLY_CUSTOMER_REPO}@|")
          
          # echo "Original URL: ${GIT_URL}"
          # echo "Modified URL: ${modified_url}"
          # echo "Repo Name: ${REPOSITORY_NAME}"
          # echo "Repo Full Name: ${SEMGREP_REPO_NAME}"
          # git clone ${modified_url} cloned-repo          
          # # show directory contents of root folder
          # ls -l cloned-repo
          # git config --global --add safe.directory /__w/nn-zcs/nn-zcs
          # cd cloned-repo
          # git status
          # export SEMGREP_REPO_NAME=$SEMGREP_REPO_NAME
          # export SEMGREP_REPO_URL=$GIT_URL
          semgrep ci
        env:
          # SEMGREP_REPO_NAME: ${{REPOSITORY_NAME}}
          # SEMGREP_REPO_URL: ${{GIT_URL}}
          # GIT_URL: ${{ github.event.client_payload.git_url }}
          # REPOSITORY_NAME: ${{ github.event.client_payload.repository_name }}
          # PAT_READ_ONLY_CUSTOMER_REPO: ${{ secrets.PAT_READ_ONLY_CUSTOMER_REPO }}
          # SEMGREP_REPO_URL: ${{ github.event.client_payload.git_url }}
          # SEMGREP_REPO_NAME: ${{ github.event.client_payload.repository_full_name }}
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
